# Generated by Django 3.2.15 on 2022-08-10 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_chat_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='title',
            field=models.TextField(default='chattitle'),
        ),
    ]
