# Generated by Django 3.2.15 on 2022-08-25 12:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_chat_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='title',
        ),
        migrations.AddField(
            model_name='chat',
            name='roomid',
            field=models.CharField(default='ZZZZZZ', max_length=6),
        ),
        migrations.AlterField(
            model_name='chat',
            name='published_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
